# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5384215e4e707e57b354a5b5bf17b90fe0ea51170498bc46800d908264bb74367625f5e3ea75e8e187cbd0fb6fd46fd9813c713f4415cd8e9701a859fc0b06d0

test:
  secret_key_base: 43dcb369e3b993d1f9767a084abed39fc21cc74af83d642dbac9c279e5e16321a222bc576fc27463fd6b1c19a9423b261d4a4004db35a300fbfbf72c26ffe035

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
